# -*- coding: utf-8 -*-
"""current2classicMAGICHOURBOUNTY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wX_TSw9Q-n28HmimSkrCHCx0CJjKeCo

current2classic
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q faiss-cpu datasets transformers gradio pillow matplotlib scikit-learn opencv-python-headless tqdm

import os
import json
import time
import numpy as np
import faiss
import torch
import cv2
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from PIL import Image
from io import BytesIO
from datasets import load_dataset
from transformers import CLIPProcessor, CLIPModel
from sklearn.preprocessing import normalize
from tqdm.auto import tqdm
import gradio as gr
import warnings
warnings.filterwarnings('ignore')

# ── Configuration ──────────────────────────────────────────────────────────────
DATASET_SIZE   = 3000    # paintings to index (↑ for better match quality)
TOP_K          = 10      # results to return
BATCH_SIZE     = 32      # embedding batch size
INDEX_DIR      = 'painting_index'
CLIP_MODEL_ID  = 'openai/clip-vit-large-patch14'
DEVICE         = 'cuda' if torch.cuda.is_available() else 'cpu'

# Similarity weights (must sum to 1.0)
W_CLIP  = 0.60  # semantic / visual vibe
W_COLOR = 0.25  # HSV color palette
W_COMP  = 0.15  # spatial composition

print(f"Device : {DEVICE}")
print(f"Dataset: {DATASET_SIZE} paintings")
print(f"Model  : {CLIP_MODEL_ID}")

print("Loading CLIP model...")
clip_model     = CLIPModel.from_pretrained(CLIP_MODEL_ID).to(DEVICE).eval()
clip_processor = CLIPProcessor.from_pretrained(CLIP_MODEL_ID)
EMBED_DIM      = clip_model.config.projection_dim  # 768 for ViT-L/14
print(f"✅ CLIP loaded  |  embed dim: {EMBED_DIM}  |  device: {DEVICE}")

STYLE_LABELS = [
    'Abstract Expressionism', 'Action Painting', 'Analytical Cubism',
    'Art Nouveau', 'Baroque', 'Color Field Painting', 'Contemporary Realism',
    'Cubism', 'Early Renaissance', 'Expressionism', 'Fauvism',
    'High Renaissance', 'Impressionism', 'Mannerism / Late Renaissance',
    'Minimalism', 'Naïve Art / Primitivism', 'New Realism',
    'Northern Renaissance', 'Pointillism', 'Pop Art', 'Post-Impressionism',
    'Realism', 'Rococo', 'Romanticism', 'Symbolism',
    'Synthetic Cubism', 'Ukiyo-e'
]

GENRE_LABELS = [
    'Abstract', 'Cityscape', 'Flower Painting', 'Genre Painting',
    'Illustration', 'Landscape', 'Nude Painting', 'Portrait',
    'Religious Painting', 'Sketch & Study', 'Still Life'
]

def decode_label(idx, label_list, fallback='Unknown'):
    if isinstance(idx, int) and 0 <= idx < len(label_list):
        return label_list[idx]
    return fallback

print(f"Styles : {len(STYLE_LABELS)}")
print(f"Genres : {len(GENRE_LABELS)}")

print(f"Streaming WikiArt ({DATASET_SIZE} paintings)...")
dataset = load_dataset('huggan/wikiart', split='train', streaming=True)

paintings_meta = []  # metadata dicts
images_raw     = []  # PIL images (kept in memory for display)

pbar = tqdm(total=DATASET_SIZE, desc='Loading')
for item in dataset:
    if len(paintings_meta) >= DATASET_SIZE:
        break
    try:
        img = item['image']
        if img is None or img.size[0] < 64 or img.size[1] < 64:
            continue
        img_rgb = img.convert('RGB')

        style_idx  = item.get('style',  -1)
        genre_idx  = item.get('genre',  -1)
        artist_idx = item.get('artist', -1)

        n = len(paintings_meta)
        paintings_meta.append({
            'id'    : n,
            'title' : f'WikiArt #{n}',
            'artist': f'Artist #{artist_idx}' if artist_idx >= 0 else 'Unknown',
            'style' : decode_label(style_idx,  STYLE_LABELS),
            'genre' : decode_label(genre_idx,  GENRE_LABELS),
        })
        images_raw.append(img_rgb)
        pbar.update(1)
    except Exception:
        continue
pbar.close()

print(f"\n✅ {len(paintings_meta)} paintings loaded")
print(f"   Unique styles : {len(set(p['style'] for p in paintings_meta))}")
print(f"   Unique genres : {len(set(p['genre'] for p in paintings_meta))}")

"""### Load Additional Dataset: European Art"""

print(f"Streaming European Art dataset...")
# Load the new dataset
eur_dataset = load_dataset('biglam/european_art', split='train', streaming=True)

# Let's say we want to add another 2000 images from this dataset
EXTRA_DATASET_SIZE = 2000

pbar = tqdm(total=EXTRA_DATASET_SIZE, desc='Loading Euro Art')
for item in eur_dataset:
    if len(paintings_meta) >= DATASET_SIZE + EXTRA_DATASET_SIZE:
        break
    try:
        # The image column might have a different name, usually 'image'
        img = item['image']
        if img is None or img.size[0] < 64 or img.size[1] < 64:
            continue
        img_rgb = img.convert('RGB')

        # Extract metadata (adjust keys based on the dataset's structure)
        title = item.get('title', 'Unknown Title')
        artist = item.get('artist', 'Unknown Artist')

        n = len(paintings_meta)
        paintings_meta.append({
            'id'    : n,
            'title' : f'{title} (#{n})',
            'artist': artist,
            'style' : 'European Art', # Fallback style
            'genre' : 'Unknown',      # Fallback genre
        })
        images_raw.append(img_rgb)
        pbar.update(1)
    except Exception as e:
        continue
pbar.close()

print(f"\n✅ Total paintings loaded now: {len(paintings_meta)}")

def clip_embed_images(pil_images: list, model, processor, device, batch_size=32) -> np.ndarray:
    """Batch-encode PIL images with CLIP. Returns L2-normalised float32 array."""
    all_vecs = []
    for i in range(0, len(pil_images), batch_size):
        batch  = pil_images[i:i+batch_size]
        inputs = processor(images=batch, return_tensors='pt', padding=True).to(device)
        with torch.no_grad():
            feats = model.get_image_features(**inputs)
            # The `clip_embed_images` in cell `vUk7SROZaPOI` was already fixed to handle BaseModelOutputWithPooling.
            # Assuming `model.get_image_features` here directly returns a tensor or BaseModelOutputWithPooling
            # whose `pooler_output` is the tensor. Applying the same logic for safety.
            if hasattr(feats, 'pooler_output') and feats.pooler_output is not None:
                feats = feats.pooler_output
            feats = feats / feats.norm(dim=-1, keepdim=True)  # L2 norm
        all_vecs.append(feats.cpu().numpy().astype(np.float32))
    return np.vstack(all_vecs)


def clip_embed_single(pil_img, model, processor, device) -> np.ndarray:
    """Embed a single PIL image. Returns shape (1, dim)."""
    return clip_embed_images([pil_img], model, processor, device, batch_size=1)


def clip_embed_text(text: str, model, processor, device) -> np.ndarray:
    """Encode a text query with CLIP. Returns shape (1, dim)."""
    inputs = processor(text=[text], return_tensors='pt', padding=True).to(device)
    with torch.no_grad():
        feats = model.get_text_features(**inputs)
        # Fix: Access the actual tensor from the BaseModelOutputWithPooling object
        if hasattr(feats, 'pooler_output') and feats.pooler_output is not None:
            feats = feats.pooler_output
        feats = feats / feats.norm(dim=-1, keepdim=True)
    return feats.cpu().numpy().astype(np.float32)


def color_histogram(pil_img: Image.Image, bins: int = 32) -> np.ndarray:
    """Normalised HSV histogram. Returns float32 vector of length bins*3."""
    arr = np.array(pil_img.resize((224, 224)))
    hsv = cv2.cvtColor(arr, cv2.COLOR_RGB2HSV)
    h = cv2.calcHist([hsv], [0], None, [bins], [0, 180]).flatten()
    s = cv2.calcHist([hsv], [1], None, [bins], [0, 256]).flatten()
    v = cv2.calcHist([hsv], [2], None, [bins], [0, 256]).flatten()
    hist = np.concatenate([h, s, v]).astype(np.float32)
    hist /= hist.sum() + 1e-8
    return hist


def composition_features(pil_img: Image.Image, grid: int = 4) -> np.ndarray:
    """Edge-density per grid cell, L2-normalised. Returns float32 vector."""
    arr  = np.array(pil_img.resize((224, 224)))
    gray = cv2.cvtColor(arr, cv2.COLOR_RGB2GRAY)
    edges= cv2.Canny(gray, 50, 150)
    h, w = edges.shape
    ch, cw = h // grid, w // grid
    feats = np.array([
        edges[i*ch:(i+1)*ch, j*cw:(j+1)*cw].mean() / 255.0
        for i in range(grid) for j in range(grid)
    ], dtype=np.float32)
    norm = np.linalg.norm(feats) + 1e-8
    return feats / norm


print("✅ Feature extraction helpers ready")

os.makedirs(INDEX_DIR, exist_ok=True)

clip_path  = f'{INDEX_DIR}/clip.index'
color_path = f'{INDEX_DIR}/color.index'
comp_path  = f'{INDEX_DIR}/comp.index'
meta_path  = f'{INDEX_DIR}/metadata.json'
cnpy_path  = f'{INDEX_DIR}/color_norms.npy'
fnpy_path  = f'{INDEX_DIR}/comp_feats.npy'

# Helper function for CLIP embeddings - redefined here to fix the AttributeError
def clip_embed_images(pil_images: list, model, processor, device, batch_size=32) -> np.ndarray:
    """Batch-encode PIL images with CLIP. Returns L2-normalised float32 array."""
    all_vecs = []
    for i in range(0, len(pil_images), batch_size):
        batch  = pil_images[i:i+batch_size]
        inputs = processor(images=batch, return_tensors='pt', padding=True).to(device)
        with torch.no_grad():
            feats_output = model.get_image_features(**inputs)
            # Fix: Access the actual tensor from the BaseModelOutputWithPooling object
            # Standard CLIPModel.get_image_features returns a tensor directly, so this
            # handling addresses an unexpected wrapping based on the error message.
            if hasattr(feats_output, 'pooler_output') and feats_output.pooler_output is not None:
                feats = feats_output.pooler_output
            else:
                feats = feats_output # Fallback: assume it's already a tensor
            feats = feats / feats.norm(dim=-1, keepdim=True)  # L2 norm
        all_vecs.append(feats.cpu().numpy().astype(np.float32))
    return np.vstack(all_vecs)

if all(os.path.exists(p) for p in [clip_path, color_path, comp_path, meta_path]):
    print("📂 Loading cached indexes...")
    clip_index  = faiss.read_index(clip_path)
    color_index = faiss.read_index(color_path)
    comp_index  = faiss.read_index(comp_path)
    color_norms = np.load(cnpy_path)
    comp_feats  = np.load(fnpy_path)
    with open(meta_path) as f:
        paintings_meta = json.load(f)
    print(f"✅ Loaded  {clip_index.ntotal} vectors")
else:
    # ── CLIP embeddings ────────────────────────────────────────────────────────
    print("Computing CLIP embeddings...")
    t0 = time.time()
    clip_embs = []
    for i in tqdm(range(0, len(images_raw), BATCH_SIZE), desc='CLIP'):
        batch = images_raw[i:i+BATCH_SIZE]
        clip_embs.append(clip_embed_images(batch, clip_model, clip_processor, DEVICE, BATCH_SIZE))
    clip_embs = np.vstack(clip_embs)

    # ── Color + composition features ──────────────────────────────────────────
    print("Computing color & composition features...")
    color_hists = np.array([color_histogram(img) for img in tqdm(images_raw, desc='Color')])
    comp_feats  = np.array([composition_features(img) for img in tqdm(images_raw, desc='Comp')])
    color_norms = normalize(color_hists, norm='l2').astype(np.float32)

    print(f"Embeddings done in {time.time()-t0:.1f}s")

    # ── Build FAISS indexes ────────────────────────────────────────────────────
    clip_index  = faiss.IndexFlatIP(clip_embs.shape[1])
    color_index = faiss.IndexFlatIP(color_norms.shape[1])
    comp_index  = faiss.IndexFlatIP(comp_feats.shape[1])
    clip_index.add(clip_embs)
    color_index.add(color_norms)
    comp_index.add(comp_feats)

    # ── Persist ────────────────────────────────────────────────────────────────
    faiss.write_index(clip_index,  clip_path)
    faiss.write_index(color_index, color_path)
    faiss.write_index(comp_index,  comp_path)
    np.save(cnpy_path, color_norms)
    np.save(fnpy_path, comp_feats)
    with open(meta_path, 'w') as f:
        json.dump(paintings_meta, f)

    print(f"\n✅ Indexes built & saved to '{INDEX_DIR}/'")
    print(f"   CLIP  : {clip_index.ntotal} vectors, dim={clip_embs.shape[1]}")
    print(f"   Color : {color_index.ntotal} vectors, dim={color_norms.shape[1]}")
    print(f"   Comp  : {comp_index.ntotal} vectors, dim={comp_feats.shape[1]}")

print("\n📌 To scale without full reindex: load existing indexes, compute new embeddings,"
      " then call index.add(new_vecs)")

def search_paintings(
    query_vec:   np.ndarray,
    query_color: np.ndarray,
    query_comp:  np.ndarray,
    top_k:    int   = TOP_K,
    w_clip:   float = W_CLIP,
    w_color:  float = W_COLOR,
    w_comp:   float = W_COMP,
    candidates_mult: int = 5,
) -> list[dict]:
    """
    Multi-dimensional painting search.
    1. Retrieve `top_k * candidates_mult` candidates from CLIP index.
    2. Re-rank by weighted combination of CLIP + color + composition scores.
    """
    # Normalise weights
    total = w_clip + w_color + w_comp
    w_clip, w_color, w_comp = w_clip/total, w_color/total, w_comp/total

    n_cand = min(top_k * candidates_mult, len(paintings_meta))
    clip_scores, clip_idx = clip_index.search(query_vec, n_cand)

    q_color_norm = normalize(query_color.reshape(1, -1), norm='l2').astype(np.float32).flatten()
    q_comp_flat  = query_comp.flatten()

    results = []
    for rank, idx in enumerate(clip_idx[0]):
        idx = int(idx)
        s_clip  = float(clip_scores[0][rank])
        s_color = float(np.dot(q_color_norm, color_norms[idx]))
        s_comp  = float(np.dot(q_comp_flat,  comp_feats[idx]))
        score   = w_clip * s_clip + w_color * s_color + w_comp * s_comp

        results.append({
            **paintings_meta[idx],
            'score'      : round(score,   4),
            'score_clip' : round(s_clip,  4),
            'score_color': round(s_color, 4),
            'score_comp' : round(s_comp,  4),
            '_idx'       : idx,
        })

    results.sort(key=lambda x: x['score'], reverse=True)
    return results[:top_k]


def search_by_image(pil_img: Image.Image, top_k=TOP_K, w_clip=W_CLIP, w_color=W_COLOR, w_comp=W_COMP):
    """Full pipeline: PIL image → ranked painting results."""
    img_rgb = pil_img.convert('RGB')
    q_clip  = clip_embed_single(img_rgb, clip_model, clip_processor, DEVICE)
    q_color = color_histogram(img_rgb)
    q_comp  = composition_features(img_rgb)
    return search_paintings(q_clip, q_color, q_comp, top_k, w_clip, w_color, w_comp)


def search_by_text(query_text: str, top_k=TOP_K):
    """CLIP text-to-painting search (CLIP-only, no color/comp)."""
    q_vec   = clip_embed_text(query_text, clip_model, clip_processor, DEVICE)
    scores, indices = clip_index.search(q_vec, top_k)
    results = []
    for rank, idx in enumerate(indices[0]):
        idx = int(idx)
        results.append({
            **paintings_meta[idx],
            'score'      : round(float(scores[0][rank]), 4),
            'score_clip' : round(float(scores[0][rank]), 4),
            'score_color': 0.0,
            'score_comp' : 0.0,
            '_idx'       : idx,
        })
    return results


print("✅ Search engine ready")

def plot_results(query_img: Image.Image, results: list, title='Photo → Painting Matcher'):
    """Render query + top-K matches in a dark-theme matplotlib grid."""
    n = len(results)
    cols = 5
    rows = (n + cols - 1) // cols

    fig = plt.figure(figsize=(22, 4 + rows * 4.5), facecolor='#0f0f0f')
    fig.suptitle(title, fontsize=20, fontweight='bold', color='white', y=0.99)

    outer = gridspec.GridSpec(
        1, 2, width_ratios=[1, 4], wspace=0.04,
        left=0.01, right=0.99, top=0.94, bottom=0.01
    )

    # Query
    ax_q = fig.add_subplot(outer[0])
    ax_q.imshow(query_img)
    ax_q.set_title('YOUR PHOTO', color='#64ffda', fontsize=12, fontweight='bold', pad=8)
    ax_q.axis('off')
    for sp in ax_q.spines.values():
        sp.set_visible(True); sp.set_edgecolor('#64ffda'); sp.set_linewidth(2.5)

    # Results grid
    inner = gridspec.GridSpecFromSubplotSpec(
        rows, cols, subplot_spec=outer[1], wspace=0.18, hspace=0.55
    )
    for i, r in enumerate(results):
        row, col = divmod(i, cols)
        ax = fig.add_subplot(inner[row, col])
        ax.imshow(images_raw[r['_idx']])
        ax.axis('off')

        sc = r['score']
        c  = '#00e676' if sc >= 0.65 else ('#ffeb3b' if sc >= 0.45 else '#ff5252')
        ax.set_title(f"#{i+1}  {sc:.3f}", color=c, fontsize=9, fontweight='bold', pad=3)

        meta = f"{r['style']}\n{r['genre']}\nC:{r['score_clip']:.2f} Col:{r['score_color']:.2f} Cmp:{r['score_comp']:.2f}"
        ax.text(0.5, -0.04, meta, transform=ax.transAxes,
                fontsize=6.5, ha='center', va='top', color='#aaaaaa', fontfamily='monospace')
        for sp in ax.spines.values():
            sp.set_visible(True); sp.set_edgecolor(c); sp.set_linewidth(1.5)

    fig.patch.set_facecolor('#0f0f0f')
    plt.show()

    # Scores table
    print(f"\n{'#':<4} {'Overall':>8} {'CLIP':>7} {'Color':>7} {'Comp':>7}  {'Style':<28} Genre")
    print('-' * 80)
    for i, r in enumerate(results):
        print(f"{i+1:<4} {r['score']:>8.4f} {r['score_clip']:>7.4f} "
              f"{r['score_color']:>7.4f} {r['score_comp']:>7.4f}  "
              f"{r['style']:<28} {r['genre']}")

print("✅ Visualiser ready")

"""test for matplotlib"""

from google.colab import files
from IPython.display import display as ipy_display

print("📤 Upload any photo:")
uploaded = files.upload()

for fname, data in uploaded.items():
    print(f"\n🔍 Processing '{fname}'...")
    query_img = Image.open(BytesIO(data)).convert('RGB')

    t0 = time.time()
    results = search_by_image(query_img)
    print(f"⚡ Search: {time.time()-t0:.2f}s")

    plot_results(query_img, results)

#@title Similarity Weight Tuning { run: "auto" }
w_semantic    = 0.8 #@param {type:"slider", min:0.0, max:1.0, step:0.05}
w_color_pal   = 0.25 #@param {type:"slider", min:0.0, max:1.0, step:0.05}
w_composition = 0.15 #@param {type:"slider", min:0.0, max:1.0, step:0.05}

if 'query_img' in dir():
    results = search_by_image(query_img, w_clip=w_semantic, w_color=w_color_pal, w_comp=w_composition)
    plot_results(query_img, results,
                 title=f'Weights — Semantic:{w_semantic} Color:{w_color_pal} Comp:{w_composition}')
else:
    print("⚠️  Run cell 10 first to upload a photo.")

TEXT_QUERY = "people dancing in a bar" #@param {type:"string"}

print(f'🔍 Text search: "{TEXT_QUERY}"\n')
text_results = search_by_text(TEXT_QUERY, top_k=10)

fig, axes = plt.subplots(2, 5, figsize=(22, 10), facecolor='#0f0f0f')
fig.suptitle(f'Text → Painting: "{TEXT_QUERY}"',
             fontsize=15, fontweight='bold', color='white')
for ax, r in zip(axes.flat, text_results):
    ax.imshow(images_raw[r['_idx']])
    ax.set_title(f"#{text_results.index(r)+1}  ({r['score']:.3f})\n{r['style']}",
                 fontsize=8, color='#64ffda', pad=3)
    ax.axis('off')
plt.tight_layout()
plt.show()

import gradio as gr
from PIL import ImageDraw, ImageFont

# ── Helpers ────────────────────────────────────────────────────────────────────

def make_result_card(pil_img: Image.Image, meta: dict, rank: int) -> Image.Image:
    """Add a score + metadata caption strip to a painting thumbnail."""
    thumb = pil_img.copy()
    thumb.thumbnail((400, 400))
    w, h = thumb.size

    # Caption strip
    strip_h = 56
    card = Image.new('RGB', (w, h + strip_h), color='#111111')
    card.paste(thumb, (0, 0))
    draw = ImageDraw.Draw(card)

    score = meta['score']
    bar_color = ('#00e676' if score >= 0.65 else
                 '#ffeb3b' if score >= 0.45 else '#ff5252')
    draw.rectangle([(0, h), (w, h + 4)], fill=bar_color)

    line1 = f"#{rank}  {score:.3f}  |  {meta['style']}"
    line2 = f"{meta['genre']}  ·  CLIP:{meta['score_clip']:.2f} Col:{meta['score_color']:.2f} Cmp:{meta['score_comp']:.2f}"
    draw.text((6, h + 6),  line1, fill='white')
    draw.text((6, h + 28), line2, fill='#aaaaaa')

    return card


def gradio_image_search(upload, w_clip, w_color, w_comp, top_k):
    if upload is None:
        return [], "Upload a photo first."
    pil_img = Image.fromarray(upload).convert('RGB') if not isinstance(upload, Image.Image) else upload
    t0 = time.time()
    results = search_by_image(pil_img, top_k=int(top_k),
                               w_clip=w_clip, w_color=w_color, w_comp=w_comp)
    elapsed = time.time() - t0
    gallery = [make_result_card(images_raw[r['_idx']], r, i+1)
               for i, r in enumerate(results)]
    summary = (f"⚡ {elapsed:.2f}s  |  {len(results)} matches  |  "
               f"Weights — CLIP:{w_clip:.2f} Color:{w_color:.2f} Comp:{w_comp:.2f}")
    return gallery, summary


def gradio_text_search(query_text, top_k):
    if not query_text.strip():
        return [], "Enter a text description first."
    results = search_by_text(query_text.strip(), top_k=int(top_k))
    gallery = [make_result_card(images_raw[r['_idx']], r, i+1)
               for i, r in enumerate(results)]
    return gallery, f"{len(results)} matches for: \"{query_text}\""


# ── UI ─────────────────────────────────────────────────────────────────────────

CSS = """
.gradio-container { font-family: 'IBM Plex Mono', monospace !important; background: #0a0a0a !important; }
h1 { color: #64ffda !important; letter-spacing: 2px; }
.gr-button-primary { background: #64ffda !important; color: #000 !important; font-weight: 700; }
.gr-slider input { accent-color: #64ffda; }
"""

with gr.Blocks(css=CSS, title='Photo → Painting Matcher') as demo:
    gr.Markdown(
        """# 🎨 PHOTO → PAINTING MATCHER
Upload any photo — sports, portraits, landscapes — and find its classical painting twin.
> *Inspired by [@artbutmakeitsports](https://www.instagram.com/artbutmakeitsports/)*"""
    )

    with gr.Tab('📸 Image Search'):
        with gr.Row():
            with gr.Column(scale=1):
                img_input = gr.Image(label='Upload Photo', type='pil')
                top_k_sl  = gr.Slider(1, 20, value=10, step=1, label='Top K results')
                gr.Markdown('**Similarity Weights** (auto-normalised)')
                w_clip_sl  = gr.Slider(0.0, 1.0, value=0.60, step=0.05, label='CLIP (semantic + visual)')
                w_color_sl = gr.Slider(0.0, 1.0, value=0.25, step=0.05, label='Color palette')
                w_comp_sl  = gr.Slider(0.0, 1.0, value=0.15, step=0.05, label='Composition')
                search_btn = gr.Button('🔍 Find Paintings', variant='primary')
            with gr.Column(scale=2):
                gallery    = gr.Gallery(label='Top Matches', columns=5, height='auto')
                status_box = gr.Textbox(label='Status', interactive=False)

        search_btn.click(
            gradio_image_search,
            inputs=[img_input, w_clip_sl, w_color_sl, w_comp_sl, top_k_sl],
            outputs=[gallery, status_box]
        )

    with gr.Tab('🔤 Text Search'):
        with gr.Row():
            with gr.Column(scale=1):
                text_input  = gr.Textbox(label='Describe a painting...', placeholder='e.g. a dramatic battle scene at sunset')
                top_k_txt   = gr.Slider(1, 20, value=10, step=1, label='Top K results')
                text_btn    = gr.Button('🔍 Search', variant='primary')
            with gr.Column(scale=2):
                gallery_txt = gr.Gallery(label='Matches', columns=5, height='auto')
                status_txt  = gr.Textbox(label='Status', interactive=False)

        text_btn.click(
            gradio_text_search,
            inputs=[text_input, top_k_txt],
            outputs=[gallery_txt, status_txt]
        )

    gr.Markdown(
        f"""---
**Dataset:** {len(paintings_meta)} WikiArt paintings
**Model:** `{CLIP_MODEL_ID}`
**Indexes:** CLIP (dim={EMBED_DIM}) + HSV Color + Spatial Composition"""
    )

demo.launch(share=True, debug=False)